/**
 * Tech Stack — knowledge-base copy.
 *
 * Mirrors `src/data/tech-constants.ts` from the portfolio (names only; icon paths are
 * irrelevant for retrieval), plus the stack used in current roles that the portfolio
 * grid does not render. Regenerate whenever the portfolio tech list changes.
 */

export type TechItem = {
  name: string;
};

export const TECH_STACK: TechItem[] = [
  { name: 'AWS' },
  { name: 'Google Cloud Platform' },
  { name: 'Next.js' },
  { name: 'React JS' },
  { name: 'Git' },
  { name: 'Github' },
  { name: 'Hono' },
  { name: 'TypeScript' },
  { name: 'Express.js' },
  { name: 'JavaScript' },
  { name: 'MongoDB' },
  { name: 'Socket.IO' },
  { name: 'SWR' },
  { name: 'Vercel' },
  { name: 'Tailwind CSS' },
  { name: 'Zustand' },
  { name: 'Nodemailer' },
  { name: 'Prisma' },
  { name: 'MySQL' },
  { name: 'PostgreSQL' },
  { name: 'Docker' },
  { name: 'React Native' },
  { name: 'HTML 5' },
  { name: 'CSS' },
  { name: 'React' },
  { name: 'Framer Motion' },
  { name: 'Python' },
  { name: 'Streamlit' },
  { name: 'Tableau' },
  { name: 'Chroma' },
  { name: 'Jira' },
  { name: 'Excel' },
  { name: 'Spreadsheets' },
  { name: 'scikit-learn' },
  { name: 'LangGraph' },
  { name: 'FAISS' },
  { name: 'Groq' },
  { name: 'C++' },
  { name: 'Java' },
  { name: 'Figma' },
  { name: 'Node.js' },
  { name: 'Firebase' },
  { name: 'Expo' },
  { name: 'Expo Orbit' },
  { name: 'Notion' },
  { name: 'Test Flight' },
  { name: 'Markdown' },
  { name: 'Jupyter' },
  { name: 'SQL' },
  { name: 'Terminal' },
  { name: 'FastAPI' },
  { name: 'Cloudflare' },
  { name: 'Terraform' },
  { name: 'Kubernetes' },
  { name: 'GitHub Actions' },
  { name: 'Amplify' },
  { name: 'Cognito' },
  { name: 'DynamoDB' },
  { name: 'Lambda' },
  { name: 'S3' },
  { name: 'Vertex AI' },
  { name: 'TanStack Query' },
  { name: 'Redux' },
  { name: 'LangChain' },
  { name: 'TensorFlow' },
  { name: 'Keras' },
  { name: 'Hugging Face' },
  { name: 'OpenAI API' },
  { name: 'Swagger' },
  { name: 'Jest' },
  { name: 'ESLint' },
  { name: 'Nginx' },
  { name: 'Linux' },
  { name: 'Bash' },
  { name: 'NumPy' },
  { name: 'Pandas' },
  { name: 'Matplotlib' },
  { name: 'Vision Camera' },
  { name: 'Roboflow' },
  { name: 'YOLO' },
];
